### ISSUE TITLE
removing/purging horizon packages removed all containers

### ISSUE THREAD

**Issue by linggao** [open-horizon/horizon-deb-packager#172]

**Comment by TheMosquito** [comment]
A quick fix to this problem would be to use a naming convention for the containers Horizon starts, and then using a container name wildcard when removing containers.  This quick approach still risks accidentally removing the wrong containers (and users would need to be careful in their container naming to avoid this problem).  I would like to suggest that instead Horizon should be carefully taking note of the actual container IDs of every container it starts, and then only removing those containers by ID later (because it knows that it started those exact containers).
